name: solarwindvariability

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - astropy=4.2
  - h5py==3.1.0
  - httplib2==0.19.0
  - matplotlib=3.3.4
  - numpy=1.20.1
  - numba=0.53.0
  - pandas=1.2.3
  - pyhdf==0.10.2
  - scipy=1.6.0
  - urllib3=1.26.8
  
